[tool.poetry]
name = "apis-instance-gideon"
version = "0.1.0"
description = "Some APIS instance"
authors = ["Birger Schacht"]
license = "MIT"
packages = [{include = "apis_ontology"}]

[tool.poetry.dependencies]
python = "^3.11"
apis-core-rdf = "0.34.1"
apis-acdhch-default-settings = "1.8.0"
psycopg2 = "^2.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
