[tool.poetry]
name = "apis-instance-gideon"
version = "0.1.0"
description = "Some APIS instance"
authors = ["Birger Schacht"]
license = "MIT"
packages = [{include = "apis_ontology"}]

[tool.poetry.dependencies]
python = "^3.11"
apis-core = { git = "https://github.com/acdh-oeaw/apis-core-rdf.git", rev = "v0.15.1" }
apis-acdhch-default-settings = "^0.1.24"
psycopg2 = "^2.9.9"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
